From python:3.9

WORKDIR C:\Users\uttam\OneDrive\Desktop\chat_bot

# Copy requirements file
Copy requirements.txt ./

#Install dependencies
Run pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD [“python”, “.py”]
