From python:3.10

WORKDIR C:\Users\uttam\OneDrive\Desktop\chat_bot

# Copy requirements file
COPY requirements.txt ./

#Install dependencies
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "/chat.py"]


# docker build -t my-ml-model .
# docker run -p 4000:80 my-ml-model